name: Sell
version: 1.0.4
author: Terpz710
api: 5.0.0
main: terpz710\sell\Main
description: Sell, SellAll, SellHand and AutoSell.

permissions:
  sell.hand:
    default: true
  sell.items:
    default: true
  sell.all:
    default: true
  sell.autosell:
    default: true
