name: Sell
version: 1.0.3
author: Terpz710
contributors: 
  - Wildan-Dev461
  - Jorgebyte
api: 5.0.0
main: terpz710\sell\Main
description: Sell, SellAll, SellHand and AutoSell.

permissions:
  sell.hand:
    default: true
  sell.items:
    default: true
  sell.all:
    default: true
  sell.autosell:
    default: true
