name: Sell
version: 1.0.0
author: Terpz710, Wildan-Dev461
api: 5.0.0
main: Terpz710\Sell\Main
description: Sell, SellAll ect.

permissions:
  sell.command.sell:
    description: Allows the player to sell their items specified through items.yml
    default: true
  sell.command.sellall:
    description: Allows the player to sell all items in their inventory
    default: true
